# Generated by Django 5.1.5 on 2025-09-23 07:10

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('political_party', '0004_alter_politicalparty_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='political_figures/photos/')),
                ('contact_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepal mobile number. The number must start with one of the following prefixes: 984, 985, 986, 974, 975, 980, 981, 982, 961, 988, 972, 963, followed by 7 digits.', regex=re.compile('^(984|985|986|974|975|980|981|982|961|988|972|963)\\d{7}$'))])),
                ('website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('current_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_politicians', to='core.address')),
                ('home_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_politicians', to='core.address')),
                ('political_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='political_party.politicalparty')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Political Figure',
                'verbose_name_plural': 'Political Figures',
                'db_table': 'political_figure',
                'ordering': ['-created_at'],
            },
        ),
    ]
