# Generated by Django 5.1.5 on 2025-10-28 10:58

import apps.political_figure.models.achievements
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_figure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('academic', 'Academic'), ('public_service', 'Public Service'), ('military', 'Military'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(validators=[apps.political_figure.models.achievements.validate_4_digit_year])),
                ('awarding_body', models.CharField(max_length=255)),
                ('evidence_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('political_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='political_figure.politicalfigure')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'political_figure_achievement',
                'ordering': ['-year', 'title'],
                'unique_together': {('political_figure', 'title', 'year')},
            },
        ),
    ]
