# Generated by Django 5.1.5 on 2025-09-20 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Political Party', 'verbose_name_plural': 'Political Parties'},
        ),
        migrations.AddConstraint(
            model_name='politicalparty',
            constraint=models.CheckConstraint(condition=models.Q(('founded_date__lt', models.F('dissolved_date')), ('dissolved_date__isnull', True), _connector='OR'), name='founded_date_before_dissolved_date_or_active'),
        ),
        migrations.AlterModelTable(
            name='politicalparty',
            table='political_party',
        ),
    ]
