# Generated by Django 5.1.5 on 2025-09-21 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_party', '0002_alter_politicalparty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
