# Generated by Django 5.1.5 on 2025-09-21 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_party', '0003_politicalparty_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
