# Generated by Django 5.1.5 on 2025-09-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super'), (2, 'Admin'), (3, 'General'), (4, 'Whistle Blower'), (5, 'Fact Checker')], default=3),
        ),
    ]
