# Generated by Django 5.1.5 on 2025-09-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
